# Generated by Django 2.2.4 on 2023-01-20 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=45)),
                ('Description', models.TextField()),
                ('used_for', models.TextField()),
                ('Advantages', models.TextField()),
                ('Datasheet', models.FileField(upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ManyToManyField(related_name='alt_products', to='product_app.Company')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_product_uploaded', to='product_app.Engineer')),
            ],
        ),
    ]
