# Generated by Django 2.2.4 on 2023-01-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_altproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='engineer',
        ),
    ]
