# Generated by Django 2.2.4 on 2023-01-21 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_engineer_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='altproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_products', to='product_app.Product'),
        ),
    ]
