# Generated by Django 2.2.4 on 2023-01-22 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_altproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineer_reviews', to='product_app.User'),
        ),
    ]
