# Generated by Django 2.2.4 on 2023-01-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_review_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineer_reviews', to='product_app.Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='product_app.Product'),
        ),
    ]
