-- MySQL Script generated by MySQL Workbench
-- Wed Dec  7 21:56:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Blogs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Blogs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Blogs` DEFAULT CHARACTER SET utf8 ;
USE `Blogs` ;

-- -----------------------------------------------------
-- Table `Blogs`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blogs`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blogs`.`blogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blogs`.`blogs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `crated_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blogs`.`Users_manage_Blogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blogs`.`Users_manage_Blogs` (
  `User_id` INT NOT NULL,
  `Blog_id` INT NOT NULL,
  PRIMARY KEY (`User_id`, `Blog_id`),
  INDEX `fk_Users_has_Blogs_Blogs1_idx` (`Blog_id` ASC) VISIBLE,
  INDEX `fk_Users_has_Blogs_Users_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Blogs_Users`
    FOREIGN KEY (`User_id`)
    REFERENCES `Blogs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Blogs_Blogs1`
    FOREIGN KEY (`Blog_id`)
    REFERENCES `Blogs`.`blogs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blogs`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blogs`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `blog_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_blogs1_idx` (`blog_id` ASC) VISIBLE,
  INDEX `fk_posts_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_blogs1`
    FOREIGN KEY (`blog_id`)
    REFERENCES `Blogs`.`blogs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Blogs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blogs`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blogs`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_posts1_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_comments_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `Blogs`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Blogs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blogs`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blogs`.`files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_files_posts1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_files_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `Blogs`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blogs`.`users_visit_blogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blogs`.`users_visit_blogs` (
  `user_id` INT NOT NULL,
  `blog_id` INT NOT NULL,
  `date_visited` DATE NULL,
  `duration` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`, `blog_id`),
  INDEX `fk_users_has_blogs_blogs1_idx` (`blog_id` ASC) VISIBLE,
  INDEX `fk_users_has_blogs_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_blogs_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Blogs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_blogs_blogs1`
    FOREIGN KEY (`blog_id`)
    REFERENCES `Blogs`.`blogs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
