# Generated by Django 2.2.4 on 2022-12-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='Taskuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Appointments', to='app_one.User'),
        ),
    ]
