# Generated by Django 2.2.4 on 2022-12-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV_SHOWS_APP', '0002_auto_20221223_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='Release_date',
            field=models.DateTimeField(),
        ),
    ]
